// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RaftRpc.proto

#include "RaftRpc.pb.h"
#include "RaftRpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace RaftRpc {

static const char* RaftRpc_method_names[] = {
  "/RaftRpc.RaftRpc/RequestVote",
  "/RaftRpc.RaftRpc/PreVote",
  "/RaftRpc.RaftRpc/AppendEntries",
  "/RaftRpc.RaftRpc/InstallSnapshot",
};

std::unique_ptr< RaftRpc::Stub> RaftRpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RaftRpc::Stub> stub(new RaftRpc::Stub(channel, options));
  return stub;
}

RaftRpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestVote_(RaftRpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PreVote_(RaftRpc_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AppendEntries_(RaftRpc_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_InstallSnapshot_(RaftRpc_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status RaftRpc::Stub::RequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::RaftRpc::RequestVoteReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RaftRpc::RequestVoteArgs, ::RaftRpc::RequestVoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestVote_, context, request, response);
}

void RaftRpc::Stub::async::RequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs* request, ::RaftRpc::RequestVoteReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RaftRpc::RequestVoteArgs, ::RaftRpc::RequestVoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, request, response, std::move(f));
}

void RaftRpc::Stub::async::RequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs* request, ::RaftRpc::RequestVoteReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RaftRpc::RequestVoteReply>* RaftRpc::Stub::PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RaftRpc::RequestVoteReply, ::RaftRpc::RequestVoteArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestVote_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RaftRpc::RequestVoteReply>* RaftRpc::Stub::AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestVoteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RaftRpc::Stub::PreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::RaftRpc::PreVoteReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::RaftRpc::PreVoteArgs, ::RaftRpc::PreVoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PreVote_, context, request, response);
}

void RaftRpc::Stub::async::PreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs* request, ::RaftRpc::PreVoteReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::RaftRpc::PreVoteArgs, ::RaftRpc::PreVoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PreVote_, context, request, response, std::move(f));
}

void RaftRpc::Stub::async::PreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs* request, ::RaftRpc::PreVoteReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PreVote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RaftRpc::PreVoteReply>* RaftRpc::Stub::PrepareAsyncPreVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RaftRpc::PreVoteReply, ::RaftRpc::PreVoteArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PreVote_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RaftRpc::PreVoteReply>* RaftRpc::Stub::AsyncPreVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPreVoteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* RaftRpc::Stub::AppendEntriesRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>::Create(channel_.get(), rpcmethod_AppendEntries_, context);
}

void RaftRpc::Stub::async::AppendEntries(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::RaftRpc::AppendEntriesArgs,::RaftRpc::AppendEntriesReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::RaftRpc::AppendEntriesArgs,::RaftRpc::AppendEntriesReply>::Create(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* RaftRpc::Stub::AsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>::Create(channel_.get(), cq, rpcmethod_AppendEntries_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* RaftRpc::Stub::PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>::Create(channel_.get(), cq, rpcmethod_AppendEntries_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* RaftRpc::Stub::InstallSnapshotRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>::Create(channel_.get(), rpcmethod_InstallSnapshot_, context);
}

void RaftRpc::Stub::async::InstallSnapshot(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::RaftRpc::InstallSnapshotArgs,::RaftRpc::InstallSnapshotReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::RaftRpc::InstallSnapshotArgs,::RaftRpc::InstallSnapshotReply>::Create(stub_->channel_.get(), stub_->rpcmethod_InstallSnapshot_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* RaftRpc::Stub::AsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>::Create(channel_.get(), cq, rpcmethod_InstallSnapshot_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* RaftRpc::Stub::PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>::Create(channel_.get(), cq, rpcmethod_InstallSnapshot_, context, false, nullptr);
}

RaftRpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftRpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftRpc::Service, ::RaftRpc::RequestVoteArgs, ::RaftRpc::RequestVoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RaftRpc::RequestVoteArgs* req,
             ::RaftRpc::RequestVoteReply* resp) {
               return service->RequestVote(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftRpc_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftRpc::Service, ::RaftRpc::PreVoteArgs, ::RaftRpc::PreVoteReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RaftRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::RaftRpc::PreVoteArgs* req,
             ::RaftRpc::PreVoteReply* resp) {
               return service->PreVote(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftRpc_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RaftRpc::Service, ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>(
          [](RaftRpc::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::RaftRpc::AppendEntriesReply,
             ::RaftRpc::AppendEntriesArgs>* stream) {
               return service->AppendEntries(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftRpc_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< RaftRpc::Service, ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>(
          [](RaftRpc::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::RaftRpc::InstallSnapshotReply,
             ::RaftRpc::InstallSnapshotArgs>* stream) {
               return service->InstallSnapshot(ctx, stream);
             }, this)));
}

RaftRpc::Service::~Service() {
}

::grpc::Status RaftRpc::Service::RequestVote(::grpc::ServerContext* context, const ::RaftRpc::RequestVoteArgs* request, ::RaftRpc::RequestVoteReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftRpc::Service::PreVote(::grpc::ServerContext* context, const ::RaftRpc::PreVoteArgs* request, ::RaftRpc::PreVoteReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftRpc::Service::AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::RaftRpc::AppendEntriesReply, ::RaftRpc::AppendEntriesArgs>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftRpc::Service::InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::RaftRpc::InstallSnapshotReply, ::RaftRpc::InstallSnapshotArgs>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace RaftRpc

