// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: KVServer.proto

#include "KVServer.pb.h"
#include "KVServer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ServerRpc {

static const char* KVServerRpc_method_names[] = {
  "/ServerRpc.KVServerRpc/Get",
  "/ServerRpc.KVServerRpc/PutAppend",
};

std::unique_ptr< KVServerRpc::Stub> KVServerRpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KVServerRpc::Stub> stub(new KVServerRpc::Stub(channel, options));
  return stub;
}

KVServerRpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Get_(KVServerRpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PutAppend_(KVServerRpc_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KVServerRpc::Stub::Get(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::ServerRpc::GetReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ServerRpc::GetArgs, ::ServerRpc::GetReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void KVServerRpc::Stub::async::Get(::grpc::ClientContext* context, const ::ServerRpc::GetArgs* request, ::ServerRpc::GetReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ServerRpc::GetArgs, ::ServerRpc::GetReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void KVServerRpc::Stub::async::Get(::grpc::ClientContext* context, const ::ServerRpc::GetArgs* request, ::ServerRpc::GetReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ServerRpc::GetReply>* KVServerRpc::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ServerRpc::GetReply, ::ServerRpc::GetArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ServerRpc::GetReply>* KVServerRpc::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status KVServerRpc::Stub::PutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::ServerRpc::PutAppendReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ServerRpc::PutAppendArgs, ::ServerRpc::PutAppendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PutAppend_, context, request, response);
}

void KVServerRpc::Stub::async::PutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs* request, ::ServerRpc::PutAppendReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ServerRpc::PutAppendArgs, ::ServerRpc::PutAppendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PutAppend_, context, request, response, std::move(f));
}

void KVServerRpc::Stub::async::PutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs* request, ::ServerRpc::PutAppendReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PutAppend_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ServerRpc::PutAppendReply>* KVServerRpc::Stub::PrepareAsyncPutAppendRaw(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ServerRpc::PutAppendReply, ::ServerRpc::PutAppendArgs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PutAppend_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ServerRpc::PutAppendReply>* KVServerRpc::Stub::AsyncPutAppendRaw(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPutAppendRaw(context, request, cq);
  result->StartCall();
  return result;
}

KVServerRpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVServerRpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVServerRpc::Service, ::ServerRpc::GetArgs, ::ServerRpc::GetReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KVServerRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ServerRpc::GetArgs* req,
             ::ServerRpc::GetReply* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVServerRpc_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVServerRpc::Service, ::ServerRpc::PutAppendArgs, ::ServerRpc::PutAppendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KVServerRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ServerRpc::PutAppendArgs* req,
             ::ServerRpc::PutAppendReply* resp) {
               return service->PutAppend(ctx, req, resp);
             }, this)));
}

KVServerRpc::Service::~Service() {
}

::grpc::Status KVServerRpc::Service::Get(::grpc::ServerContext* context, const ::ServerRpc::GetArgs* request, ::ServerRpc::GetReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVServerRpc::Service::PutAppend(::grpc::ServerContext* context, const ::ServerRpc::PutAppendArgs* request, ::ServerRpc::PutAppendReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ServerRpc

