// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: KVServer.proto
#ifndef GRPC_KVServer_2eproto__INCLUDED
#define GRPC_KVServer_2eproto__INCLUDED

#include "KVServer.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ServerRpc {

class KVServerRpc final {
 public:
  static constexpr char const* service_full_name() {
    return "ServerRpc.KVServerRpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Get(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::ServerRpc::GetReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::GetReply>> AsyncGet(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::GetReply>>(AsyncGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::GetReply>> PrepareAsyncGet(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::GetReply>>(PrepareAsyncGetRaw(context, request, cq));
    }
    virtual ::grpc::Status PutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::ServerRpc::PutAppendReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::PutAppendReply>> AsyncPutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::PutAppendReply>>(AsyncPutAppendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::PutAppendReply>> PrepareAsyncPutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::PutAppendReply>>(PrepareAsyncPutAppendRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Get(::grpc::ClientContext* context, const ::ServerRpc::GetArgs* request, ::ServerRpc::GetReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Get(::grpc::ClientContext* context, const ::ServerRpc::GetArgs* request, ::ServerRpc::GetReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void PutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs* request, ::ServerRpc::PutAppendReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs* request, ::ServerRpc::PutAppendReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::GetReply>* AsyncGetRaw(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::GetReply>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::PutAppendReply>* AsyncPutAppendRaw(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ServerRpc::PutAppendReply>* PrepareAsyncPutAppendRaw(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Get(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::ServerRpc::GetReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerRpc::GetReply>> AsyncGet(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerRpc::GetReply>>(AsyncGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerRpc::GetReply>> PrepareAsyncGet(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerRpc::GetReply>>(PrepareAsyncGetRaw(context, request, cq));
    }
    ::grpc::Status PutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::ServerRpc::PutAppendReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerRpc::PutAppendReply>> AsyncPutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerRpc::PutAppendReply>>(AsyncPutAppendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerRpc::PutAppendReply>> PrepareAsyncPutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerRpc::PutAppendReply>>(PrepareAsyncPutAppendRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Get(::grpc::ClientContext* context, const ::ServerRpc::GetArgs* request, ::ServerRpc::GetReply* response, std::function<void(::grpc::Status)>) override;
      void Get(::grpc::ClientContext* context, const ::ServerRpc::GetArgs* request, ::ServerRpc::GetReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs* request, ::ServerRpc::PutAppendReply* response, std::function<void(::grpc::Status)>) override;
      void PutAppend(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs* request, ::ServerRpc::PutAppendReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ServerRpc::GetReply>* AsyncGetRaw(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ServerRpc::GetReply>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::ServerRpc::GetArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ServerRpc::PutAppendReply>* AsyncPutAppendRaw(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ServerRpc::PutAppendReply>* PrepareAsyncPutAppendRaw(::grpc::ClientContext* context, const ::ServerRpc::PutAppendArgs& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Get_;
    const ::grpc::internal::RpcMethod rpcmethod_PutAppend_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Get(::grpc::ServerContext* context, const ::ServerRpc::GetArgs* request, ::ServerRpc::GetReply* response);
    virtual ::grpc::Status PutAppend(::grpc::ServerContext* context, const ::ServerRpc::PutAppendArgs* request, ::ServerRpc::PutAppendReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Get() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::ServerRpc::GetArgs* /*request*/, ::ServerRpc::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::ServerRpc::GetArgs* request, ::grpc::ServerAsyncResponseWriter< ::ServerRpc::GetReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PutAppend() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::ServerRpc::PutAppendArgs* /*request*/, ::ServerRpc::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutAppend(::grpc::ServerContext* context, ::ServerRpc::PutAppendArgs* request, ::grpc::ServerAsyncResponseWriter< ::ServerRpc::PutAppendReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Get<WithAsyncMethod_PutAppend<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Get() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ServerRpc::GetArgs, ::ServerRpc::GetReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ServerRpc::GetArgs* request, ::ServerRpc::GetReply* response) { return this->Get(context, request, response); }));}
    void SetMessageAllocatorFor_Get(
        ::grpc::MessageAllocator< ::ServerRpc::GetArgs, ::ServerRpc::GetReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ServerRpc::GetArgs, ::ServerRpc::GetReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::ServerRpc::GetArgs* /*request*/, ::ServerRpc::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::ServerRpc::GetArgs* /*request*/, ::ServerRpc::GetReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PutAppend() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ServerRpc::PutAppendArgs, ::ServerRpc::PutAppendReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ServerRpc::PutAppendArgs* request, ::ServerRpc::PutAppendReply* response) { return this->PutAppend(context, request, response); }));}
    void SetMessageAllocatorFor_PutAppend(
        ::grpc::MessageAllocator< ::ServerRpc::PutAppendArgs, ::ServerRpc::PutAppendReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ServerRpc::PutAppendArgs, ::ServerRpc::PutAppendReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::ServerRpc::PutAppendArgs* /*request*/, ::ServerRpc::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PutAppend(
      ::grpc::CallbackServerContext* /*context*/, const ::ServerRpc::PutAppendArgs* /*request*/, ::ServerRpc::PutAppendReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Get<WithCallbackMethod_PutAppend<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Get() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::ServerRpc::GetArgs* /*request*/, ::ServerRpc::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PutAppend() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::ServerRpc::PutAppendArgs* /*request*/, ::ServerRpc::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Get() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::ServerRpc::GetArgs* /*request*/, ::ServerRpc::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PutAppend() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::ServerRpc::PutAppendArgs* /*request*/, ::ServerRpc::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutAppend(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Get() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Get(context, request, response); }));
    }
    ~WithRawCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::ServerRpc::GetArgs* /*request*/, ::ServerRpc::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PutAppend() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PutAppend(context, request, response); }));
    }
    ~WithRawCallbackMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::ServerRpc::PutAppendArgs* /*request*/, ::ServerRpc::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PutAppend(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Get() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ServerRpc::GetArgs, ::ServerRpc::GetReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ServerRpc::GetArgs, ::ServerRpc::GetReply>* streamer) {
                       return this->StreamedGet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::ServerRpc::GetArgs* /*request*/, ::ServerRpc::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ServerRpc::GetArgs,::ServerRpc::GetReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PutAppend() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ServerRpc::PutAppendArgs, ::ServerRpc::PutAppendReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ServerRpc::PutAppendArgs, ::ServerRpc::PutAppendReply>* streamer) {
                       return this->StreamedPutAppend(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::ServerRpc::PutAppendArgs* /*request*/, ::ServerRpc::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPutAppend(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ServerRpc::PutAppendArgs,::ServerRpc::PutAppendReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_PutAppend<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_PutAppend<Service > > StreamedService;
};

}  // namespace ServerRpc


#endif  // GRPC_KVServer_2eproto__INCLUDED
