// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RaftRpc.proto
#ifndef GRPC_RaftRpc_2eproto__INCLUDED
#define GRPC_RaftRpc_2eproto__INCLUDED

#include "RaftRpc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace RaftRpc {

class RaftRpc final {
 public:
  static constexpr char const* service_full_name() {
    return "RaftRpc.RaftRpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::RaftRpc::RequestVoteReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::RequestVoteReply>> AsyncRequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::RequestVoteReply>>(AsyncRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::RequestVoteReply>> PrepareAsyncRequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::RequestVoteReply>>(PrepareAsyncRequestVoteRaw(context, request, cq));
    }
    virtual ::grpc::Status PreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::RaftRpc::PreVoteReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::PreVoteReply>> AsyncPreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::PreVoteReply>>(AsyncPreVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::PreVoteReply>> PrepareAsyncPreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::PreVoteReply>>(PrepareAsyncPreVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>> AppendEntries(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>>(AppendEntriesRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>> AsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>>(AsyncAppendEntriesRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>>(PrepareAsyncAppendEntriesRaw(context, cq));
    }
    // AppendEntries用双向流
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>> InstallSnapshot(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>>(InstallSnapshotRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>> AsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>>(AsyncInstallSnapshotRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>>(PrepareAsyncInstallSnapshotRaw(context, cq));
    }
    // InstallSnapshot用单向流
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs* request, ::RaftRpc::RequestVoteReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs* request, ::RaftRpc::RequestVoteReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void PreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs* request, ::RaftRpc::PreVoteReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs* request, ::RaftRpc::PreVoteReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AppendEntries(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::RaftRpc::AppendEntriesArgs,::RaftRpc::AppendEntriesReply>* reactor) = 0;
      // AppendEntries用双向流
      virtual void InstallSnapshot(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::RaftRpc::InstallSnapshotArgs,::RaftRpc::InstallSnapshotReply>* reactor) = 0;
      // InstallSnapshot用单向流
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::RequestVoteReply>* AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::RequestVoteReply>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::PreVoteReply>* AsyncPreVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::RaftRpc::PreVoteReply>* PrepareAsyncPreVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* AppendEntriesRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* InstallSnapshotRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::RaftRpc::RequestVoteReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RaftRpc::RequestVoteReply>> AsyncRequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RaftRpc::RequestVoteReply>>(AsyncRequestVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RaftRpc::RequestVoteReply>> PrepareAsyncRequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RaftRpc::RequestVoteReply>>(PrepareAsyncRequestVoteRaw(context, request, cq));
    }
    ::grpc::Status PreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::RaftRpc::PreVoteReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RaftRpc::PreVoteReply>> AsyncPreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RaftRpc::PreVoteReply>>(AsyncPreVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RaftRpc::PreVoteReply>> PrepareAsyncPreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::RaftRpc::PreVoteReply>>(PrepareAsyncPreVoteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>> AppendEntries(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>>(AppendEntriesRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>> AsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>>(AsyncAppendEntriesRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>> PrepareAsyncAppendEntries(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>>(PrepareAsyncAppendEntriesRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>> InstallSnapshot(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>>(InstallSnapshotRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>> AsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>>(AsyncInstallSnapshotRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>> PrepareAsyncInstallSnapshot(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>>(PrepareAsyncInstallSnapshotRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs* request, ::RaftRpc::RequestVoteReply* response, std::function<void(::grpc::Status)>) override;
      void RequestVote(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs* request, ::RaftRpc::RequestVoteReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs* request, ::RaftRpc::PreVoteReply* response, std::function<void(::grpc::Status)>) override;
      void PreVote(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs* request, ::RaftRpc::PreVoteReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AppendEntries(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::RaftRpc::AppendEntriesArgs,::RaftRpc::AppendEntriesReply>* reactor) override;
      void InstallSnapshot(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::RaftRpc::InstallSnapshotArgs,::RaftRpc::InstallSnapshotReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::RaftRpc::RequestVoteReply>* AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RaftRpc::RequestVoteReply>* PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::RequestVoteArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RaftRpc::PreVoteReply>* AsyncPreVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::RaftRpc::PreVoteReply>* PrepareAsyncPreVoteRaw(::grpc::ClientContext* context, const ::RaftRpc::PreVoteArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* AppendEntriesRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* AsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* InstallSnapshotRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* AsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestVote_;
    const ::grpc::internal::RpcMethod rpcmethod_PreVote_;
    const ::grpc::internal::RpcMethod rpcmethod_AppendEntries_;
    const ::grpc::internal::RpcMethod rpcmethod_InstallSnapshot_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RequestVote(::grpc::ServerContext* context, const ::RaftRpc::RequestVoteArgs* request, ::RaftRpc::RequestVoteReply* response);
    virtual ::grpc::Status PreVote(::grpc::ServerContext* context, const ::RaftRpc::PreVoteArgs* request, ::RaftRpc::PreVoteReply* response);
    virtual ::grpc::Status AppendEntries(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::RaftRpc::AppendEntriesReply, ::RaftRpc::AppendEntriesArgs>* stream);
    // AppendEntries用双向流
    virtual ::grpc::Status InstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::RaftRpc::InstallSnapshotReply, ::RaftRpc::InstallSnapshotArgs>* stream);
    // InstallSnapshot用单向流
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RequestVote() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::RequestVoteArgs* /*request*/, ::RaftRpc::RequestVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::RaftRpc::RequestVoteArgs* request, ::grpc::ServerAsyncResponseWriter< ::RaftRpc::RequestVoteReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PreVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PreVote() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PreVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PreVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::PreVoteArgs* /*request*/, ::RaftRpc::PreVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPreVote(::grpc::ServerContext* context, ::RaftRpc::PreVoteArgs* request, ::grpc::ServerAsyncResponseWriter< ::RaftRpc::PreVoteReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AppendEntries() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::AppendEntriesReply, ::RaftRpc::AppendEntriesArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::RaftRpc::AppendEntriesReply, ::RaftRpc::AppendEntriesArgs>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::InstallSnapshotReply, ::RaftRpc::InstallSnapshotArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::RaftRpc::InstallSnapshotReply, ::RaftRpc::InstallSnapshotArgs>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RequestVote<WithAsyncMethod_PreVote<WithAsyncMethod_AppendEntries<WithAsyncMethod_InstallSnapshot<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RequestVote() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::RaftRpc::RequestVoteArgs, ::RaftRpc::RequestVoteReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RaftRpc::RequestVoteArgs* request, ::RaftRpc::RequestVoteReply* response) { return this->RequestVote(context, request, response); }));}
    void SetMessageAllocatorFor_RequestVote(
        ::grpc::MessageAllocator< ::RaftRpc::RequestVoteArgs, ::RaftRpc::RequestVoteReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RaftRpc::RequestVoteArgs, ::RaftRpc::RequestVoteReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::RequestVoteArgs* /*request*/, ::RaftRpc::RequestVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestVote(
      ::grpc::CallbackServerContext* /*context*/, const ::RaftRpc::RequestVoteArgs* /*request*/, ::RaftRpc::RequestVoteReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PreVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PreVote() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::RaftRpc::PreVoteArgs, ::RaftRpc::PreVoteReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::RaftRpc::PreVoteArgs* request, ::RaftRpc::PreVoteReply* response) { return this->PreVote(context, request, response); }));}
    void SetMessageAllocatorFor_PreVote(
        ::grpc::MessageAllocator< ::RaftRpc::PreVoteArgs, ::RaftRpc::PreVoteReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::RaftRpc::PreVoteArgs, ::RaftRpc::PreVoteReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PreVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PreVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::PreVoteArgs* /*request*/, ::RaftRpc::PreVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PreVote(
      ::grpc::CallbackServerContext* /*context*/, const ::RaftRpc::PreVoteArgs* /*request*/, ::RaftRpc::PreVoteReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AppendEntries() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->AppendEntries(context); }));
    }
    ~WithCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::AppendEntriesReply, ::RaftRpc::AppendEntriesArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::RaftRpc::AppendEntriesArgs, ::RaftRpc::AppendEntriesReply>* AppendEntries(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->InstallSnapshot(context); }));
    }
    ~WithCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::InstallSnapshotReply, ::RaftRpc::InstallSnapshotArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::RaftRpc::InstallSnapshotArgs, ::RaftRpc::InstallSnapshotReply>* InstallSnapshot(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_RequestVote<WithCallbackMethod_PreVote<WithCallbackMethod_AppendEntries<WithCallbackMethod_InstallSnapshot<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RequestVote() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::RequestVoteArgs* /*request*/, ::RaftRpc::RequestVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PreVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PreVote() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PreVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PreVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::PreVoteArgs* /*request*/, ::RaftRpc::PreVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AppendEntries() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::AppendEntriesReply, ::RaftRpc::AppendEntriesArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::InstallSnapshotReply, ::RaftRpc::InstallSnapshotArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RequestVote() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::RequestVoteArgs* /*request*/, ::RaftRpc::RequestVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestVote(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PreVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PreVote() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PreVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PreVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::PreVoteArgs* /*request*/, ::RaftRpc::PreVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPreVote(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AppendEntries() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::AppendEntriesReply, ::RaftRpc::AppendEntriesArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendEntries(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::InstallSnapshotReply, ::RaftRpc::InstallSnapshotArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInstallSnapshot(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RequestVote() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RequestVote(context, request, response); }));
    }
    ~WithRawCallbackMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::RequestVoteArgs* /*request*/, ::RaftRpc::RequestVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestVote(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PreVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PreVote() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PreVote(context, request, response); }));
    }
    ~WithRawCallbackMethod_PreVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PreVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::PreVoteArgs* /*request*/, ::RaftRpc::PreVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PreVote(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AppendEntries : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AppendEntries() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->AppendEntries(context); }));
    }
    ~WithRawCallbackMethod_AppendEntries() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendEntries(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::AppendEntriesReply, ::RaftRpc::AppendEntriesArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* AppendEntries(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InstallSnapshot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InstallSnapshot() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->InstallSnapshot(context); }));
    }
    ~WithRawCallbackMethod_InstallSnapshot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InstallSnapshot(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::RaftRpc::InstallSnapshotReply, ::RaftRpc::InstallSnapshotArgs>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* InstallSnapshot(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RequestVote() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RaftRpc::RequestVoteArgs, ::RaftRpc::RequestVoteReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RaftRpc::RequestVoteArgs, ::RaftRpc::RequestVoteReply>* streamer) {
                       return this->StreamedRequestVote(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RequestVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::RequestVoteArgs* /*request*/, ::RaftRpc::RequestVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestVote(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RaftRpc::RequestVoteArgs,::RaftRpc::RequestVoteReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PreVote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PreVote() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::RaftRpc::PreVoteArgs, ::RaftRpc::PreVoteReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::RaftRpc::PreVoteArgs, ::RaftRpc::PreVoteReply>* streamer) {
                       return this->StreamedPreVote(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PreVote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PreVote(::grpc::ServerContext* /*context*/, const ::RaftRpc::PreVoteArgs* /*request*/, ::RaftRpc::PreVoteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPreVote(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::RaftRpc::PreVoteArgs,::RaftRpc::PreVoteReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RequestVote<WithStreamedUnaryMethod_PreVote<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RequestVote<WithStreamedUnaryMethod_PreVote<Service > > StreamedService;
};

}  // namespace RaftRpc


#endif  // GRPC_RaftRpc_2eproto__INCLUDED
