// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RaftRpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_RaftRpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_RaftRpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_RaftRpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_RaftRpc_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RaftRpc_2eproto;
namespace RaftRpc {
class AppendEntriesArgs;
struct AppendEntriesArgsDefaultTypeInternal;
extern AppendEntriesArgsDefaultTypeInternal _AppendEntriesArgs_default_instance_;
class AppendEntriesReply;
struct AppendEntriesReplyDefaultTypeInternal;
extern AppendEntriesReplyDefaultTypeInternal _AppendEntriesReply_default_instance_;
class InstallSnapshotArgs;
struct InstallSnapshotArgsDefaultTypeInternal;
extern InstallSnapshotArgsDefaultTypeInternal _InstallSnapshotArgs_default_instance_;
class InstallSnapshotReply;
struct InstallSnapshotReplyDefaultTypeInternal;
extern InstallSnapshotReplyDefaultTypeInternal _InstallSnapshotReply_default_instance_;
class LogEntry;
struct LogEntryDefaultTypeInternal;
extern LogEntryDefaultTypeInternal _LogEntry_default_instance_;
class RequestVoteArgs;
struct RequestVoteArgsDefaultTypeInternal;
extern RequestVoteArgsDefaultTypeInternal _RequestVoteArgs_default_instance_;
class RequestVoteReply;
struct RequestVoteReplyDefaultTypeInternal;
extern RequestVoteReplyDefaultTypeInternal _RequestVoteReply_default_instance_;
}  // namespace RaftRpc
PROTOBUF_NAMESPACE_OPEN
template<> ::RaftRpc::AppendEntriesArgs* Arena::CreateMaybeMessage<::RaftRpc::AppendEntriesArgs>(Arena*);
template<> ::RaftRpc::AppendEntriesReply* Arena::CreateMaybeMessage<::RaftRpc::AppendEntriesReply>(Arena*);
template<> ::RaftRpc::InstallSnapshotArgs* Arena::CreateMaybeMessage<::RaftRpc::InstallSnapshotArgs>(Arena*);
template<> ::RaftRpc::InstallSnapshotReply* Arena::CreateMaybeMessage<::RaftRpc::InstallSnapshotReply>(Arena*);
template<> ::RaftRpc::LogEntry* Arena::CreateMaybeMessage<::RaftRpc::LogEntry>(Arena*);
template<> ::RaftRpc::RequestVoteArgs* Arena::CreateMaybeMessage<::RaftRpc::RequestVoteArgs>(Arena*);
template<> ::RaftRpc::RequestVoteReply* Arena::CreateMaybeMessage<::RaftRpc::RequestVoteReply>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace RaftRpc {

enum RaftState : int {
  RAFT_FOLLOWER = 0,
  RAFT_CANDIDATE = 1,
  RAFT_LEADER = 2,
  RaftState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RaftState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RaftState_IsValid(int value);
constexpr RaftState RaftState_MIN = RAFT_FOLLOWER;
constexpr RaftState RaftState_MAX = RAFT_LEADER;
constexpr int RaftState_ARRAYSIZE = RaftState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RaftState_descriptor();
template<typename T>
inline const std::string& RaftState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RaftState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RaftState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RaftState_descriptor(), enum_t_value);
}
inline bool RaftState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RaftState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RaftState>(
    RaftState_descriptor(), name, value);
}
// ===================================================================

class LogEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RaftRpc.LogEntry) */ {
 public:
  inline LogEntry() : LogEntry(nullptr) {}
  ~LogEntry() override;
  explicit PROTOBUF_CONSTEXPR LogEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogEntry(const LogEntry& from);
  LogEntry(LogEntry&& from) noexcept
    : LogEntry() {
    *this = ::std::move(from);
  }

  inline LogEntry& operator=(const LogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogEntry& operator=(LogEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogEntry* internal_default_instance() {
    return reinterpret_cast<const LogEntry*>(
               &_LogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LogEntry& a, LogEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(LogEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogEntry& from) {
    LogEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RaftRpc.LogEntry";
  }
  protected:
  explicit LogEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandFieldNumber = 1,
    kLogTermFieldNumber = 2,
    kLogIndexFieldNumber = 3,
  };
  // bytes Command = 1;
  void clear_command();
  const std::string& command() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command();
  PROTOBUF_NODISCARD std::string* release_command();
  void set_allocated_command(std::string* command);
  private:
  const std::string& _internal_command() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command(const std::string& value);
  std::string* _internal_mutable_command();
  public:

  // int32 LogTerm = 2;
  void clear_logterm();
  int32_t logterm() const;
  void set_logterm(int32_t value);
  private:
  int32_t _internal_logterm() const;
  void _internal_set_logterm(int32_t value);
  public:

  // int32 LogIndex = 3;
  void clear_logindex();
  int32_t logindex() const;
  void set_logindex(int32_t value);
  private:
  int32_t _internal_logindex() const;
  void _internal_set_logindex(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RaftRpc.LogEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_;
    int32_t logterm_;
    int32_t logindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RaftRpc_2eproto;
};
// -------------------------------------------------------------------

class AppendEntriesArgs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RaftRpc.AppendEntriesArgs) */ {
 public:
  inline AppendEntriesArgs() : AppendEntriesArgs(nullptr) {}
  ~AppendEntriesArgs() override;
  explicit PROTOBUF_CONSTEXPR AppendEntriesArgs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppendEntriesArgs(const AppendEntriesArgs& from);
  AppendEntriesArgs(AppendEntriesArgs&& from) noexcept
    : AppendEntriesArgs() {
    *this = ::std::move(from);
  }

  inline AppendEntriesArgs& operator=(const AppendEntriesArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppendEntriesArgs& operator=(AppendEntriesArgs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppendEntriesArgs& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppendEntriesArgs* internal_default_instance() {
    return reinterpret_cast<const AppendEntriesArgs*>(
               &_AppendEntriesArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AppendEntriesArgs& a, AppendEntriesArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(AppendEntriesArgs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppendEntriesArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppendEntriesArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AppendEntriesArgs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AppendEntriesArgs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AppendEntriesArgs& from) {
    AppendEntriesArgs::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppendEntriesArgs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RaftRpc.AppendEntriesArgs";
  }
  protected:
  explicit AppendEntriesArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 5,
    kTermFieldNumber = 1,
    kLeaderIdFieldNumber = 2,
    kPreLogIndexFieldNumber = 3,
    kPreLogTermFieldNumber = 4,
    kLeaderCommitFieldNumber = 6,
  };
  // repeated .RaftRpc.LogEntry Entries = 5;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  ::RaftRpc::LogEntry* mutable_entries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RaftRpc::LogEntry >*
      mutable_entries();
  private:
  const ::RaftRpc::LogEntry& _internal_entries(int index) const;
  ::RaftRpc::LogEntry* _internal_add_entries();
  public:
  const ::RaftRpc::LogEntry& entries(int index) const;
  ::RaftRpc::LogEntry* add_entries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RaftRpc::LogEntry >&
      entries() const;

  // int32 Term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // int32 LeaderId = 2;
  void clear_leaderid();
  int32_t leaderid() const;
  void set_leaderid(int32_t value);
  private:
  int32_t _internal_leaderid() const;
  void _internal_set_leaderid(int32_t value);
  public:

  // int32 PreLogIndex = 3;
  void clear_prelogindex();
  int32_t prelogindex() const;
  void set_prelogindex(int32_t value);
  private:
  int32_t _internal_prelogindex() const;
  void _internal_set_prelogindex(int32_t value);
  public:

  // int32 PreLogTerm = 4;
  void clear_prelogterm();
  int32_t prelogterm() const;
  void set_prelogterm(int32_t value);
  private:
  int32_t _internal_prelogterm() const;
  void _internal_set_prelogterm(int32_t value);
  public:

  // int32 LeaderCommit = 6;
  void clear_leadercommit();
  int32_t leadercommit() const;
  void set_leadercommit(int32_t value);
  private:
  int32_t _internal_leadercommit() const;
  void _internal_set_leadercommit(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RaftRpc.AppendEntriesArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RaftRpc::LogEntry > entries_;
    int32_t term_;
    int32_t leaderid_;
    int32_t prelogindex_;
    int32_t prelogterm_;
    int32_t leadercommit_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RaftRpc_2eproto;
};
// -------------------------------------------------------------------

class AppendEntriesReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RaftRpc.AppendEntriesReply) */ {
 public:
  inline AppendEntriesReply() : AppendEntriesReply(nullptr) {}
  ~AppendEntriesReply() override;
  explicit PROTOBUF_CONSTEXPR AppendEntriesReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AppendEntriesReply(const AppendEntriesReply& from);
  AppendEntriesReply(AppendEntriesReply&& from) noexcept
    : AppendEntriesReply() {
    *this = ::std::move(from);
  }

  inline AppendEntriesReply& operator=(const AppendEntriesReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AppendEntriesReply& operator=(AppendEntriesReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AppendEntriesReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const AppendEntriesReply* internal_default_instance() {
    return reinterpret_cast<const AppendEntriesReply*>(
               &_AppendEntriesReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AppendEntriesReply& a, AppendEntriesReply& b) {
    a.Swap(&b);
  }
  inline void Swap(AppendEntriesReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AppendEntriesReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AppendEntriesReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AppendEntriesReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AppendEntriesReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AppendEntriesReply& from) {
    AppendEntriesReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppendEntriesReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RaftRpc.AppendEntriesReply";
  }
  protected:
  explicit AppendEntriesReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kSuccssFieldNumber = 2,
    kUpdateNextIndexFieldNumber = 3,
    kStatusFieldNumber = 4,
  };
  // int32 Term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // bool Succss = 2;
  void clear_succss();
  bool succss() const;
  void set_succss(bool value);
  private:
  bool _internal_succss() const;
  void _internal_set_succss(bool value);
  public:

  // int32 UpdateNextIndex = 3;
  void clear_updatenextindex();
  int32_t updatenextindex() const;
  void set_updatenextindex(int32_t value);
  private:
  int32_t _internal_updatenextindex() const;
  void _internal_set_updatenextindex(int32_t value);
  public:

  // int32 Status = 4;
  void clear_status();
  int32_t status() const;
  void set_status(int32_t value);
  private:
  int32_t _internal_status() const;
  void _internal_set_status(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RaftRpc.AppendEntriesReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    bool succss_;
    int32_t updatenextindex_;
    int32_t status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RaftRpc_2eproto;
};
// -------------------------------------------------------------------

class RequestVoteArgs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RaftRpc.RequestVoteArgs) */ {
 public:
  inline RequestVoteArgs() : RequestVoteArgs(nullptr) {}
  ~RequestVoteArgs() override;
  explicit PROTOBUF_CONSTEXPR RequestVoteArgs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RequestVoteArgs(const RequestVoteArgs& from);
  RequestVoteArgs(RequestVoteArgs&& from) noexcept
    : RequestVoteArgs() {
    *this = ::std::move(from);
  }

  inline RequestVoteArgs& operator=(const RequestVoteArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestVoteArgs& operator=(RequestVoteArgs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestVoteArgs& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestVoteArgs* internal_default_instance() {
    return reinterpret_cast<const RequestVoteArgs*>(
               &_RequestVoteArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RequestVoteArgs& a, RequestVoteArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestVoteArgs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestVoteArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestVoteArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RequestVoteArgs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RequestVoteArgs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RequestVoteArgs& from) {
    RequestVoteArgs::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestVoteArgs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RaftRpc.RequestVoteArgs";
  }
  protected:
  explicit RequestVoteArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kCandidateIdFieldNumber = 2,
    kLastLogTermFieldNumber = 3,
    kLastLogIndexFieldNumber = 4,
  };
  // int32 Term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // int32 CandidateId = 2;
  void clear_candidateid();
  int32_t candidateid() const;
  void set_candidateid(int32_t value);
  private:
  int32_t _internal_candidateid() const;
  void _internal_set_candidateid(int32_t value);
  public:

  // int32 LastLogTerm = 3;
  void clear_lastlogterm();
  int32_t lastlogterm() const;
  void set_lastlogterm(int32_t value);
  private:
  int32_t _internal_lastlogterm() const;
  void _internal_set_lastlogterm(int32_t value);
  public:

  // int32 LastLogIndex = 4;
  void clear_lastlogindex();
  int32_t lastlogindex() const;
  void set_lastlogindex(int32_t value);
  private:
  int32_t _internal_lastlogindex() const;
  void _internal_set_lastlogindex(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RaftRpc.RequestVoteArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    int32_t candidateid_;
    int32_t lastlogterm_;
    int32_t lastlogindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RaftRpc_2eproto;
};
// -------------------------------------------------------------------

class RequestVoteReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RaftRpc.RequestVoteReply) */ {
 public:
  inline RequestVoteReply() : RequestVoteReply(nullptr) {}
  ~RequestVoteReply() override;
  explicit PROTOBUF_CONSTEXPR RequestVoteReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RequestVoteReply(const RequestVoteReply& from);
  RequestVoteReply(RequestVoteReply&& from) noexcept
    : RequestVoteReply() {
    *this = ::std::move(from);
  }

  inline RequestVoteReply& operator=(const RequestVoteReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestVoteReply& operator=(RequestVoteReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestVoteReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestVoteReply* internal_default_instance() {
    return reinterpret_cast<const RequestVoteReply*>(
               &_RequestVoteReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RequestVoteReply& a, RequestVoteReply& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestVoteReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestVoteReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestVoteReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RequestVoteReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RequestVoteReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RequestVoteReply& from) {
    RequestVoteReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestVoteReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RaftRpc.RequestVoteReply";
  }
  protected:
  explicit RequestVoteReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kVoteGrantedFieldNumber = 2,
    kVoteStateFieldNumber = 3,
  };
  // int32 Term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // bool VoteGranted = 2;
  void clear_votegranted();
  bool votegranted() const;
  void set_votegranted(bool value);
  private:
  bool _internal_votegranted() const;
  void _internal_set_votegranted(bool value);
  public:

  // int32 VoteState = 3;
  void clear_votestate();
  int32_t votestate() const;
  void set_votestate(int32_t value);
  private:
  int32_t _internal_votestate() const;
  void _internal_set_votestate(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RaftRpc.RequestVoteReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    bool votegranted_;
    int32_t votestate_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RaftRpc_2eproto;
};
// -------------------------------------------------------------------

class InstallSnapshotArgs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RaftRpc.InstallSnapshotArgs) */ {
 public:
  inline InstallSnapshotArgs() : InstallSnapshotArgs(nullptr) {}
  ~InstallSnapshotArgs() override;
  explicit PROTOBUF_CONSTEXPR InstallSnapshotArgs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstallSnapshotArgs(const InstallSnapshotArgs& from);
  InstallSnapshotArgs(InstallSnapshotArgs&& from) noexcept
    : InstallSnapshotArgs() {
    *this = ::std::move(from);
  }

  inline InstallSnapshotArgs& operator=(const InstallSnapshotArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstallSnapshotArgs& operator=(InstallSnapshotArgs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstallSnapshotArgs& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstallSnapshotArgs* internal_default_instance() {
    return reinterpret_cast<const InstallSnapshotArgs*>(
               &_InstallSnapshotArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(InstallSnapshotArgs& a, InstallSnapshotArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(InstallSnapshotArgs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstallSnapshotArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstallSnapshotArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstallSnapshotArgs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InstallSnapshotArgs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InstallSnapshotArgs& from) {
    InstallSnapshotArgs::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstallSnapshotArgs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RaftRpc.InstallSnapshotArgs";
  }
  protected:
  explicit InstallSnapshotArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 5,
    kLeaderIdFieldNumber = 1,
    kTermFieldNumber = 2,
    kLastSnapShotIncludeIndexFieldNumber = 3,
    kLastSnapShotIncludeTermFieldNumber = 4,
    kOffsetFieldNumber = 6,
  };
  // bytes Data = 5;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 LeaderId = 1;
  void clear_leaderid();
  int32_t leaderid() const;
  void set_leaderid(int32_t value);
  private:
  int32_t _internal_leaderid() const;
  void _internal_set_leaderid(int32_t value);
  public:

  // int32 Term = 2;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // int32 LastSnapShotIncludeIndex = 3;
  void clear_lastsnapshotincludeindex();
  int32_t lastsnapshotincludeindex() const;
  void set_lastsnapshotincludeindex(int32_t value);
  private:
  int32_t _internal_lastsnapshotincludeindex() const;
  void _internal_set_lastsnapshotincludeindex(int32_t value);
  public:

  // int32 LastSnapShotIncludeTerm = 4;
  void clear_lastsnapshotincludeterm();
  int32_t lastsnapshotincludeterm() const;
  void set_lastsnapshotincludeterm(int32_t value);
  private:
  int32_t _internal_lastsnapshotincludeterm() const;
  void _internal_set_lastsnapshotincludeterm(int32_t value);
  public:

  // int32 Offset = 6;
  void clear_offset();
  int32_t offset() const;
  void set_offset(int32_t value);
  private:
  int32_t _internal_offset() const;
  void _internal_set_offset(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RaftRpc.InstallSnapshotArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int32_t leaderid_;
    int32_t term_;
    int32_t lastsnapshotincludeindex_;
    int32_t lastsnapshotincludeterm_;
    int32_t offset_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RaftRpc_2eproto;
};
// -------------------------------------------------------------------

class InstallSnapshotReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RaftRpc.InstallSnapshotReply) */ {
 public:
  inline InstallSnapshotReply() : InstallSnapshotReply(nullptr) {}
  ~InstallSnapshotReply() override;
  explicit PROTOBUF_CONSTEXPR InstallSnapshotReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstallSnapshotReply(const InstallSnapshotReply& from);
  InstallSnapshotReply(InstallSnapshotReply&& from) noexcept
    : InstallSnapshotReply() {
    *this = ::std::move(from);
  }

  inline InstallSnapshotReply& operator=(const InstallSnapshotReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstallSnapshotReply& operator=(InstallSnapshotReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstallSnapshotReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstallSnapshotReply* internal_default_instance() {
    return reinterpret_cast<const InstallSnapshotReply*>(
               &_InstallSnapshotReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(InstallSnapshotReply& a, InstallSnapshotReply& b) {
    a.Swap(&b);
  }
  inline void Swap(InstallSnapshotReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstallSnapshotReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstallSnapshotReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstallSnapshotReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InstallSnapshotReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InstallSnapshotReply& from) {
    InstallSnapshotReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstallSnapshotReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RaftRpc.InstallSnapshotReply";
  }
  protected:
  explicit InstallSnapshotReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
  };
  // int32 Term = 1;
  void clear_term();
  int32_t term() const;
  void set_term(int32_t value);
  private:
  int32_t _internal_term() const;
  void _internal_set_term(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:RaftRpc.InstallSnapshotReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t term_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RaftRpc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogEntry

// bytes Command = 1;
inline void LogEntry::clear_command() {
  _impl_.command_.ClearToEmpty();
}
inline const std::string& LogEntry::command() const {
  // @@protoc_insertion_point(field_get:RaftRpc.LogEntry.Command)
  return _internal_command();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogEntry::set_command(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RaftRpc.LogEntry.Command)
}
inline std::string* LogEntry::mutable_command() {
  std::string* _s = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:RaftRpc.LogEntry.Command)
  return _s;
}
inline const std::string& LogEntry::_internal_command() const {
  return _impl_.command_.Get();
}
inline void LogEntry::_internal_set_command(const std::string& value) {
  
  _impl_.command_.Set(value, GetArenaForAllocation());
}
inline std::string* LogEntry::_internal_mutable_command() {
  
  return _impl_.command_.Mutable(GetArenaForAllocation());
}
inline std::string* LogEntry::release_command() {
  // @@protoc_insertion_point(field_release:RaftRpc.LogEntry.Command)
  return _impl_.command_.Release();
}
inline void LogEntry::set_allocated_command(std::string* command) {
  if (command != nullptr) {
    
  } else {
    
  }
  _impl_.command_.SetAllocated(command, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_.IsDefault()) {
    _impl_.command_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RaftRpc.LogEntry.Command)
}

// int32 LogTerm = 2;
inline void LogEntry::clear_logterm() {
  _impl_.logterm_ = 0;
}
inline int32_t LogEntry::_internal_logterm() const {
  return _impl_.logterm_;
}
inline int32_t LogEntry::logterm() const {
  // @@protoc_insertion_point(field_get:RaftRpc.LogEntry.LogTerm)
  return _internal_logterm();
}
inline void LogEntry::_internal_set_logterm(int32_t value) {
  
  _impl_.logterm_ = value;
}
inline void LogEntry::set_logterm(int32_t value) {
  _internal_set_logterm(value);
  // @@protoc_insertion_point(field_set:RaftRpc.LogEntry.LogTerm)
}

// int32 LogIndex = 3;
inline void LogEntry::clear_logindex() {
  _impl_.logindex_ = 0;
}
inline int32_t LogEntry::_internal_logindex() const {
  return _impl_.logindex_;
}
inline int32_t LogEntry::logindex() const {
  // @@protoc_insertion_point(field_get:RaftRpc.LogEntry.LogIndex)
  return _internal_logindex();
}
inline void LogEntry::_internal_set_logindex(int32_t value) {
  
  _impl_.logindex_ = value;
}
inline void LogEntry::set_logindex(int32_t value) {
  _internal_set_logindex(value);
  // @@protoc_insertion_point(field_set:RaftRpc.LogEntry.LogIndex)
}

// -------------------------------------------------------------------

// AppendEntriesArgs

// int32 Term = 1;
inline void AppendEntriesArgs::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_term() const {
  return _impl_.term_;
}
inline int32_t AppendEntriesArgs::term() const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesArgs.Term)
  return _internal_term();
}
inline void AppendEntriesArgs::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void AppendEntriesArgs::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:RaftRpc.AppendEntriesArgs.Term)
}

// int32 LeaderId = 2;
inline void AppendEntriesArgs::clear_leaderid() {
  _impl_.leaderid_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_leaderid() const {
  return _impl_.leaderid_;
}
inline int32_t AppendEntriesArgs::leaderid() const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesArgs.LeaderId)
  return _internal_leaderid();
}
inline void AppendEntriesArgs::_internal_set_leaderid(int32_t value) {
  
  _impl_.leaderid_ = value;
}
inline void AppendEntriesArgs::set_leaderid(int32_t value) {
  _internal_set_leaderid(value);
  // @@protoc_insertion_point(field_set:RaftRpc.AppendEntriesArgs.LeaderId)
}

// int32 PreLogIndex = 3;
inline void AppendEntriesArgs::clear_prelogindex() {
  _impl_.prelogindex_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_prelogindex() const {
  return _impl_.prelogindex_;
}
inline int32_t AppendEntriesArgs::prelogindex() const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesArgs.PreLogIndex)
  return _internal_prelogindex();
}
inline void AppendEntriesArgs::_internal_set_prelogindex(int32_t value) {
  
  _impl_.prelogindex_ = value;
}
inline void AppendEntriesArgs::set_prelogindex(int32_t value) {
  _internal_set_prelogindex(value);
  // @@protoc_insertion_point(field_set:RaftRpc.AppendEntriesArgs.PreLogIndex)
}

// int32 PreLogTerm = 4;
inline void AppendEntriesArgs::clear_prelogterm() {
  _impl_.prelogterm_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_prelogterm() const {
  return _impl_.prelogterm_;
}
inline int32_t AppendEntriesArgs::prelogterm() const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesArgs.PreLogTerm)
  return _internal_prelogterm();
}
inline void AppendEntriesArgs::_internal_set_prelogterm(int32_t value) {
  
  _impl_.prelogterm_ = value;
}
inline void AppendEntriesArgs::set_prelogterm(int32_t value) {
  _internal_set_prelogterm(value);
  // @@protoc_insertion_point(field_set:RaftRpc.AppendEntriesArgs.PreLogTerm)
}

// repeated .RaftRpc.LogEntry Entries = 5;
inline int AppendEntriesArgs::_internal_entries_size() const {
  return _impl_.entries_.size();
}
inline int AppendEntriesArgs::entries_size() const {
  return _internal_entries_size();
}
inline void AppendEntriesArgs::clear_entries() {
  _impl_.entries_.Clear();
}
inline ::RaftRpc::LogEntry* AppendEntriesArgs::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:RaftRpc.AppendEntriesArgs.Entries)
  return _impl_.entries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RaftRpc::LogEntry >*
AppendEntriesArgs::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:RaftRpc.AppendEntriesArgs.Entries)
  return &_impl_.entries_;
}
inline const ::RaftRpc::LogEntry& AppendEntriesArgs::_internal_entries(int index) const {
  return _impl_.entries_.Get(index);
}
inline const ::RaftRpc::LogEntry& AppendEntriesArgs::entries(int index) const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesArgs.Entries)
  return _internal_entries(index);
}
inline ::RaftRpc::LogEntry* AppendEntriesArgs::_internal_add_entries() {
  return _impl_.entries_.Add();
}
inline ::RaftRpc::LogEntry* AppendEntriesArgs::add_entries() {
  ::RaftRpc::LogEntry* _add = _internal_add_entries();
  // @@protoc_insertion_point(field_add:RaftRpc.AppendEntriesArgs.Entries)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::RaftRpc::LogEntry >&
AppendEntriesArgs::entries() const {
  // @@protoc_insertion_point(field_list:RaftRpc.AppendEntriesArgs.Entries)
  return _impl_.entries_;
}

// int32 LeaderCommit = 6;
inline void AppendEntriesArgs::clear_leadercommit() {
  _impl_.leadercommit_ = 0;
}
inline int32_t AppendEntriesArgs::_internal_leadercommit() const {
  return _impl_.leadercommit_;
}
inline int32_t AppendEntriesArgs::leadercommit() const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesArgs.LeaderCommit)
  return _internal_leadercommit();
}
inline void AppendEntriesArgs::_internal_set_leadercommit(int32_t value) {
  
  _impl_.leadercommit_ = value;
}
inline void AppendEntriesArgs::set_leadercommit(int32_t value) {
  _internal_set_leadercommit(value);
  // @@protoc_insertion_point(field_set:RaftRpc.AppendEntriesArgs.LeaderCommit)
}

// -------------------------------------------------------------------

// AppendEntriesReply

// int32 Term = 1;
inline void AppendEntriesReply::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t AppendEntriesReply::_internal_term() const {
  return _impl_.term_;
}
inline int32_t AppendEntriesReply::term() const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesReply.Term)
  return _internal_term();
}
inline void AppendEntriesReply::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void AppendEntriesReply::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:RaftRpc.AppendEntriesReply.Term)
}

// bool Succss = 2;
inline void AppendEntriesReply::clear_succss() {
  _impl_.succss_ = false;
}
inline bool AppendEntriesReply::_internal_succss() const {
  return _impl_.succss_;
}
inline bool AppendEntriesReply::succss() const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesReply.Succss)
  return _internal_succss();
}
inline void AppendEntriesReply::_internal_set_succss(bool value) {
  
  _impl_.succss_ = value;
}
inline void AppendEntriesReply::set_succss(bool value) {
  _internal_set_succss(value);
  // @@protoc_insertion_point(field_set:RaftRpc.AppendEntriesReply.Succss)
}

// int32 UpdateNextIndex = 3;
inline void AppendEntriesReply::clear_updatenextindex() {
  _impl_.updatenextindex_ = 0;
}
inline int32_t AppendEntriesReply::_internal_updatenextindex() const {
  return _impl_.updatenextindex_;
}
inline int32_t AppendEntriesReply::updatenextindex() const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesReply.UpdateNextIndex)
  return _internal_updatenextindex();
}
inline void AppendEntriesReply::_internal_set_updatenextindex(int32_t value) {
  
  _impl_.updatenextindex_ = value;
}
inline void AppendEntriesReply::set_updatenextindex(int32_t value) {
  _internal_set_updatenextindex(value);
  // @@protoc_insertion_point(field_set:RaftRpc.AppendEntriesReply.UpdateNextIndex)
}

// int32 Status = 4;
inline void AppendEntriesReply::clear_status() {
  _impl_.status_ = 0;
}
inline int32_t AppendEntriesReply::_internal_status() const {
  return _impl_.status_;
}
inline int32_t AppendEntriesReply::status() const {
  // @@protoc_insertion_point(field_get:RaftRpc.AppendEntriesReply.Status)
  return _internal_status();
}
inline void AppendEntriesReply::_internal_set_status(int32_t value) {
  
  _impl_.status_ = value;
}
inline void AppendEntriesReply::set_status(int32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:RaftRpc.AppendEntriesReply.Status)
}

// -------------------------------------------------------------------

// RequestVoteArgs

// int32 Term = 1;
inline void RequestVoteArgs::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t RequestVoteArgs::_internal_term() const {
  return _impl_.term_;
}
inline int32_t RequestVoteArgs::term() const {
  // @@protoc_insertion_point(field_get:RaftRpc.RequestVoteArgs.Term)
  return _internal_term();
}
inline void RequestVoteArgs::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void RequestVoteArgs::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:RaftRpc.RequestVoteArgs.Term)
}

// int32 CandidateId = 2;
inline void RequestVoteArgs::clear_candidateid() {
  _impl_.candidateid_ = 0;
}
inline int32_t RequestVoteArgs::_internal_candidateid() const {
  return _impl_.candidateid_;
}
inline int32_t RequestVoteArgs::candidateid() const {
  // @@protoc_insertion_point(field_get:RaftRpc.RequestVoteArgs.CandidateId)
  return _internal_candidateid();
}
inline void RequestVoteArgs::_internal_set_candidateid(int32_t value) {
  
  _impl_.candidateid_ = value;
}
inline void RequestVoteArgs::set_candidateid(int32_t value) {
  _internal_set_candidateid(value);
  // @@protoc_insertion_point(field_set:RaftRpc.RequestVoteArgs.CandidateId)
}

// int32 LastLogTerm = 3;
inline void RequestVoteArgs::clear_lastlogterm() {
  _impl_.lastlogterm_ = 0;
}
inline int32_t RequestVoteArgs::_internal_lastlogterm() const {
  return _impl_.lastlogterm_;
}
inline int32_t RequestVoteArgs::lastlogterm() const {
  // @@protoc_insertion_point(field_get:RaftRpc.RequestVoteArgs.LastLogTerm)
  return _internal_lastlogterm();
}
inline void RequestVoteArgs::_internal_set_lastlogterm(int32_t value) {
  
  _impl_.lastlogterm_ = value;
}
inline void RequestVoteArgs::set_lastlogterm(int32_t value) {
  _internal_set_lastlogterm(value);
  // @@protoc_insertion_point(field_set:RaftRpc.RequestVoteArgs.LastLogTerm)
}

// int32 LastLogIndex = 4;
inline void RequestVoteArgs::clear_lastlogindex() {
  _impl_.lastlogindex_ = 0;
}
inline int32_t RequestVoteArgs::_internal_lastlogindex() const {
  return _impl_.lastlogindex_;
}
inline int32_t RequestVoteArgs::lastlogindex() const {
  // @@protoc_insertion_point(field_get:RaftRpc.RequestVoteArgs.LastLogIndex)
  return _internal_lastlogindex();
}
inline void RequestVoteArgs::_internal_set_lastlogindex(int32_t value) {
  
  _impl_.lastlogindex_ = value;
}
inline void RequestVoteArgs::set_lastlogindex(int32_t value) {
  _internal_set_lastlogindex(value);
  // @@protoc_insertion_point(field_set:RaftRpc.RequestVoteArgs.LastLogIndex)
}

// -------------------------------------------------------------------

// RequestVoteReply

// int32 Term = 1;
inline void RequestVoteReply::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t RequestVoteReply::_internal_term() const {
  return _impl_.term_;
}
inline int32_t RequestVoteReply::term() const {
  // @@protoc_insertion_point(field_get:RaftRpc.RequestVoteReply.Term)
  return _internal_term();
}
inline void RequestVoteReply::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void RequestVoteReply::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:RaftRpc.RequestVoteReply.Term)
}

// bool VoteGranted = 2;
inline void RequestVoteReply::clear_votegranted() {
  _impl_.votegranted_ = false;
}
inline bool RequestVoteReply::_internal_votegranted() const {
  return _impl_.votegranted_;
}
inline bool RequestVoteReply::votegranted() const {
  // @@protoc_insertion_point(field_get:RaftRpc.RequestVoteReply.VoteGranted)
  return _internal_votegranted();
}
inline void RequestVoteReply::_internal_set_votegranted(bool value) {
  
  _impl_.votegranted_ = value;
}
inline void RequestVoteReply::set_votegranted(bool value) {
  _internal_set_votegranted(value);
  // @@protoc_insertion_point(field_set:RaftRpc.RequestVoteReply.VoteGranted)
}

// int32 VoteState = 3;
inline void RequestVoteReply::clear_votestate() {
  _impl_.votestate_ = 0;
}
inline int32_t RequestVoteReply::_internal_votestate() const {
  return _impl_.votestate_;
}
inline int32_t RequestVoteReply::votestate() const {
  // @@protoc_insertion_point(field_get:RaftRpc.RequestVoteReply.VoteState)
  return _internal_votestate();
}
inline void RequestVoteReply::_internal_set_votestate(int32_t value) {
  
  _impl_.votestate_ = value;
}
inline void RequestVoteReply::set_votestate(int32_t value) {
  _internal_set_votestate(value);
  // @@protoc_insertion_point(field_set:RaftRpc.RequestVoteReply.VoteState)
}

// -------------------------------------------------------------------

// InstallSnapshotArgs

// int32 LeaderId = 1;
inline void InstallSnapshotArgs::clear_leaderid() {
  _impl_.leaderid_ = 0;
}
inline int32_t InstallSnapshotArgs::_internal_leaderid() const {
  return _impl_.leaderid_;
}
inline int32_t InstallSnapshotArgs::leaderid() const {
  // @@protoc_insertion_point(field_get:RaftRpc.InstallSnapshotArgs.LeaderId)
  return _internal_leaderid();
}
inline void InstallSnapshotArgs::_internal_set_leaderid(int32_t value) {
  
  _impl_.leaderid_ = value;
}
inline void InstallSnapshotArgs::set_leaderid(int32_t value) {
  _internal_set_leaderid(value);
  // @@protoc_insertion_point(field_set:RaftRpc.InstallSnapshotArgs.LeaderId)
}

// int32 Term = 2;
inline void InstallSnapshotArgs::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t InstallSnapshotArgs::_internal_term() const {
  return _impl_.term_;
}
inline int32_t InstallSnapshotArgs::term() const {
  // @@protoc_insertion_point(field_get:RaftRpc.InstallSnapshotArgs.Term)
  return _internal_term();
}
inline void InstallSnapshotArgs::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void InstallSnapshotArgs::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:RaftRpc.InstallSnapshotArgs.Term)
}

// int32 LastSnapShotIncludeIndex = 3;
inline void InstallSnapshotArgs::clear_lastsnapshotincludeindex() {
  _impl_.lastsnapshotincludeindex_ = 0;
}
inline int32_t InstallSnapshotArgs::_internal_lastsnapshotincludeindex() const {
  return _impl_.lastsnapshotincludeindex_;
}
inline int32_t InstallSnapshotArgs::lastsnapshotincludeindex() const {
  // @@protoc_insertion_point(field_get:RaftRpc.InstallSnapshotArgs.LastSnapShotIncludeIndex)
  return _internal_lastsnapshotincludeindex();
}
inline void InstallSnapshotArgs::_internal_set_lastsnapshotincludeindex(int32_t value) {
  
  _impl_.lastsnapshotincludeindex_ = value;
}
inline void InstallSnapshotArgs::set_lastsnapshotincludeindex(int32_t value) {
  _internal_set_lastsnapshotincludeindex(value);
  // @@protoc_insertion_point(field_set:RaftRpc.InstallSnapshotArgs.LastSnapShotIncludeIndex)
}

// int32 LastSnapShotIncludeTerm = 4;
inline void InstallSnapshotArgs::clear_lastsnapshotincludeterm() {
  _impl_.lastsnapshotincludeterm_ = 0;
}
inline int32_t InstallSnapshotArgs::_internal_lastsnapshotincludeterm() const {
  return _impl_.lastsnapshotincludeterm_;
}
inline int32_t InstallSnapshotArgs::lastsnapshotincludeterm() const {
  // @@protoc_insertion_point(field_get:RaftRpc.InstallSnapshotArgs.LastSnapShotIncludeTerm)
  return _internal_lastsnapshotincludeterm();
}
inline void InstallSnapshotArgs::_internal_set_lastsnapshotincludeterm(int32_t value) {
  
  _impl_.lastsnapshotincludeterm_ = value;
}
inline void InstallSnapshotArgs::set_lastsnapshotincludeterm(int32_t value) {
  _internal_set_lastsnapshotincludeterm(value);
  // @@protoc_insertion_point(field_set:RaftRpc.InstallSnapshotArgs.LastSnapShotIncludeTerm)
}

// bytes Data = 5;
inline void InstallSnapshotArgs::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& InstallSnapshotArgs::data() const {
  // @@protoc_insertion_point(field_get:RaftRpc.InstallSnapshotArgs.Data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InstallSnapshotArgs::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RaftRpc.InstallSnapshotArgs.Data)
}
inline std::string* InstallSnapshotArgs::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:RaftRpc.InstallSnapshotArgs.Data)
  return _s;
}
inline const std::string& InstallSnapshotArgs::_internal_data() const {
  return _impl_.data_.Get();
}
inline void InstallSnapshotArgs::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* InstallSnapshotArgs::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* InstallSnapshotArgs::release_data() {
  // @@protoc_insertion_point(field_release:RaftRpc.InstallSnapshotArgs.Data)
  return _impl_.data_.Release();
}
inline void InstallSnapshotArgs::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RaftRpc.InstallSnapshotArgs.Data)
}

// int32 Offset = 6;
inline void InstallSnapshotArgs::clear_offset() {
  _impl_.offset_ = 0;
}
inline int32_t InstallSnapshotArgs::_internal_offset() const {
  return _impl_.offset_;
}
inline int32_t InstallSnapshotArgs::offset() const {
  // @@protoc_insertion_point(field_get:RaftRpc.InstallSnapshotArgs.Offset)
  return _internal_offset();
}
inline void InstallSnapshotArgs::_internal_set_offset(int32_t value) {
  
  _impl_.offset_ = value;
}
inline void InstallSnapshotArgs::set_offset(int32_t value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:RaftRpc.InstallSnapshotArgs.Offset)
}

// -------------------------------------------------------------------

// InstallSnapshotReply

// int32 Term = 1;
inline void InstallSnapshotReply::clear_term() {
  _impl_.term_ = 0;
}
inline int32_t InstallSnapshotReply::_internal_term() const {
  return _impl_.term_;
}
inline int32_t InstallSnapshotReply::term() const {
  // @@protoc_insertion_point(field_get:RaftRpc.InstallSnapshotReply.Term)
  return _internal_term();
}
inline void InstallSnapshotReply::_internal_set_term(int32_t value) {
  
  _impl_.term_ = value;
}
inline void InstallSnapshotReply::set_term(int32_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:RaftRpc.InstallSnapshotReply.Term)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace RaftRpc

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::RaftRpc::RaftState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RaftRpc::RaftState>() {
  return ::RaftRpc::RaftState_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_RaftRpc_2eproto
